# AWS Nuke Configuration Template
# 민감한 정보를 환경변수로 관리하는 보안 템플릿

regions:
  - ap-northeast-2
  - global

blocklist:
  - "999999999"

resource-types:
  excludes:
    - IAMUser
    - IAMUserGroupAttachment
    - IAMGroup
    - IAMGroupPolicy
    - IAMGroupPolicyAttachment
    - IAMUserAccessKey
    - IAMLoginProfile
    - IAMUserMFADevice
    - IAMVirtualMFADevice

accounts:
  "${AWS_ACCOUNT_ID}": # 환경변수에서 Account ID 읽기
    filters:
      IAMUser:
        - "${IAM_USER_NAME}" # 환경변수에서 IAM User 읽기
      IAMUserPolicyAttachment:
        - "${IAM_USER_NAME} -> AdministratorAccess"
      IAMUserAccessKey:
        - "${IAM_USER_NAME} -> ${AWS_ACCESS_KEY_ID}" # 환경변수에서 Access Key 읽기

# 사용법:
# export AWS_ACCOUNT_ID="your-account-id"
# export IAM_USER_NAME="your-iam-user"
# export AWS_ACCESS_KEY_ID="your-access-key-id"
# envsubst < nuke-config.template.yml > nuke-config.yml
